# Generated by Django 5.0.6 on 2025-07-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0002_faq_newsarticle_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo_url', models.URLField()),
                ('rating', models.FloatField()),
                ('amc', models.CharField(max_length=50)),
                ('brokerage', models.CharField(max_length=50)),
                ('features', models.JSONField(default=list)),
            ],
        ),
    ]
