# Generated by Django 5.0.6 on 2025-07-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0003_broker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('read_time', models.CharField(default='5 min read', max_length=20)),
            ],
        ),
    ]
