# Generated by Django 5.0.6 on 2025-07-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0004_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broker',
            old_name='brokerage',
            new_name='account_opening_charge',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='features',
        ),
        migrations.AddField(
            model_name='broker',
            name='cons',
            field=models.TextField(default='not'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broker',
            name='customer_support',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='broker',
            name='delivery_charge',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broker',
            name='ease_of_use',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broker',
            name='intraday_charge',
            field=models.CharField(default='NOt related', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broker',
            name='pros',
            field=models.TextField(default='not'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='broker',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
