# Generated by Django 5.0.6 on 2025-07-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0005_rename_brokerage_broker_account_opening_charge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandlestickPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='candlestick_images/')),
            ],
        ),
    ]
