# Generated by Django 5.0.6 on 2025-07-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0006_candlestickpattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='chart_patterns/')),
            ],
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('posted_on', models.DateField(auto_now_add=True)),
                ('apply_link', models.URLField()),
            ],
        ),
    ]
