# Generated by Django 5.0.6 on 2025-07-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0007_chartpattern_jobopening'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartpattern',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chartpattern',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='patterns/'),
        ),
    ]
