# Generated by Django 5.0.6 on 2025-07-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0008_chartpattern_order_alter_chartpattern_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text="Bootstrap icon class, e.g. 'bi bi-envelope'", max_length=50)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
