# Generated by Django 5.0.6 on 2025-07-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0009_contactoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Large Cap', 'Large Cap'), ('Mid Cap', 'Mid Cap'), ('Debt', 'Debt'), ('Hybrid', 'Hybrid')], max_length=50)),
                ('aum', models.CharField(max_length=100)),
                ('expense_ratio', models.CharField(max_length=50)),
                ('cagr_5y', models.CharField(max_length=50)),
                ('performance', models.TextField()),
                ('risk', models.TextField()),
                ('composition', models.TextField()),
            ],
        ),
    ]
