# Generated by Django 5.0.6 on 2025-07-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0010_mutualfund'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('color', models.CharField(default='#ffffff', max_length=20)),
                ('section', models.CharField(choices=[('platforms', 'Platforms'), ('network', 'Network'), ('powerful', 'Powerful Platform')], max_length=100)),
            ],
        ),
    ]
