# Generated by Django 5.0.6 on 2025-07-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0011_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharkInvestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='investors/')),
                ('color', models.CharField(default='#d7d6fb', max_length=20)),
            ],
        ),
    ]
