# Generated by Django 5.0.6 on 2025-07-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0012_sharkinvestor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharkinvestor',
            old_name='bio',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='sharkinvestor',
            name='color',
        ),
    ]
