# Generated by Django 5.0.6 on 2025-07-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0013_rename_bio_sharkinvestor_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='technical_indicators/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
