# Generated by Django 5.0.6 on 2025-07-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0014_technicalindicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('views', models.PositiveIntegerField(default=0)),
                ('image', models.URLField(blank=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
