# Generated by Django 5.0.6 on 2025-07-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0016_loginlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('article', 'Article')], max_length=50)),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
