# Generated by Django 5.2.4 on 2025-07-16 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0017_mediaitem_alter_loginlog_login_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='features',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='account_opening_charge',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='cons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='delivery_charge',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='ease_of_use',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='broker',
            name='intraday_charge',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='pros',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactoption',
            name='icon',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
