# Generated by Django 5.2.4 on 2026-04-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipo_app', '0020_ipomodel_delete_movingaveragesection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPOModel',
        ),
    ]
